"""add dispute attachments

Revision ID: b41135480ad1
Revises: f2f3946376b7
Create Date: 2026-03-21 11:32:46.522949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b41135480ad1'
down_revision: Union[str, Sequence[str], None] = 'f2f3946376b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('dispute_attachments_dispute_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['dispute_messages.id'], name=op.f('dispute_attachments_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dispute_attachments_pkey'))
    )
    op.create_index(op.f('ix_dispute_attachments_id'), 'dispute_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_dispute_attachments_dispute_id'), 'dispute_attachments', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_attachments_message_id'), 'dispute_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispute_attachments_message_id'), table_name='dispute_attachments')
    op.create_index(op.f('ix_dispute_attachments_dispute_id'), 'dispute_attachments', ['dispute_id'], unique=False)
    op.drop_index(op.f('ix_dispute_attachments_id'), table_name='dispute_attachments')
    op.drop_table('dispute_attachments')
    # ### end Alembic commands ###
